# Welcome to the MobTweaks Plugin Config
# Feel free to modify this file to suit your mob needs

enablePlugin: true #Set to false if you want to disable to plugin

# Friendly Mob Section
breedMultiplier: 2 # Max is 10
breedMultiplyChance: .5 # This value should be between 0 and 1. Default is .5
breedMultiplierApply: #Add or remove mobs that are affected by the breedMultiplier
  - "COW"
  - "CHICKEN"
  - "SHEEP"
  - "GOAT"
  - "BEE"
  - "PARROT"
  - "AXOLOTL"

friendlyDropMultiplier: 2 # Max is 10
friendlyDropMultiplyChance: .5 # This value should be between 0 and 1. Default is .5
friendlyDropMultiplierApply: #Add or remove mobs that are affected by the friendlyDropMultiplierApply
  - "COW"
  - "CHICKEN"
  - "SHEEP"
  - "GOAT"
  - "BEE"
  - "PARROT"
  - "AXOLOTL"

enableRandomSheep: true
randomSheepChance: .1
